[project]
name = "yampit"
version = "0.3.0"
description = "Builds datasets, jumps through FDBs."
readme = "README.md"
authors = [
    { name = "Tobias Kölling", email = "tobias.koelling@mpimet.mpg.de" },
    { name = "Lukas Kluft", email = "lukas.kluft@mpimet.mpg.de" },
]
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.11.1",
    "eccodes==2.41",
    #"eccodeslib<2.44",
    "fsspec>=2025.2.0",
    "gribscan",
    "intake>=2.0.8",
    "intake-esm",
    "isodate",
    "jinja2>=3.1.5",
    "pandas>=2.3.3",
    "polytope-client>=0.7.4",
    "pyproj>=3.3.0",
    "sanic>=24.6.0",
    "zarr>=2.18.3,<3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "healpy>=1.18.0",
    "ipython>=8.29.0",
    "matplotlib>=3.9.2",
    "xarray>=2024.10.0",
]

[tool.uv.sources]
gribscan = { git = "https://github.com/observingClouds/gribscan", rev = "deode" }
intake-esm = { git = "https://github.com/observingClouds/intake-esm.git", rev = "bf250b51a" }
