services:
  backend:
    build:
      context: ../
      dockerfile: docker/yampit/Dockerfile
    env_file: ./polytope.env
    environment:
      PYTHONUNBUFFERED: '1'
  cache:
    build: varnish
    environment:
      VARNISH_SIZE: 5G
  caddy:
    image: caddy:2.9.1
    restart: always
    ports:
    - 80:80
    - 443:443
    - 443:443/udp
    volumes:
    - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    - caddy-data:/data
    - caddy-config:/config
volumes:
  caddy-data: null
  caddy-config: null
